version: "2"

services:
  nginx:
    build: ./nginx
    image: chainify/engine-nginx
    container_name: engine-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/nginx.conf
      - ~/.data/sqlite/chainify:/opt/db
    depends_on:
      - api
      - postgres
      - parser
      - ipfs
    restart: unless-stopped

  api:
    build: ./server
    image: chainify/engine-api
    container_name: engine-api
    volumes:
      - ./server:/opt
      - ./server/config.ini:/opt/config.ini
      - ~/.data/leveldb/chainify/messenger:/root/.data/leveldb/messenger
      - ~/.data/leveldb/chainify/sql:/root/.data/leveldb/sql
    command: bash -c "python3.7 server.py"
    depends_on:
      - ipfs
      - postgres
    tty: true
    stdin_open: true
    restart: unless-stopped

  postgres:
    build: ./postgresql
    image: chainify/engine-postgres
    container_name: engine-postgres
    volumes:
      - ~/.data/chainify/postgres:/var/lib/postgresql/data
      - ./postgresql/postgresql.conf:/etc/postgresql/postgresql.conf
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=chainify
      - POSTGRES_USER=chainify
      - POSTGRES_PASSWORD=chainify
    tty: true
    stdin_open: true
    restart: unless-stopped

  redis:
    build: ./redis
    image: chainify/engine-redis
    container_name: engine-redis
    volumes:
      - ~/.data/chainify/redis:/data
    ports:
      - 6379:6379
    tty: true
    stdin_open: true
    restart: unless-stopped

  parser:
    build: ./parser
    image: chainify/engine-parser
    container_name: engine-parser
    volumes:
      - ./parser:/opt
    depends_on:
      - postgres
      - ipfs
    command: bash -c "python3.7 server.py"
    tty: true
    stdin_open: true
    labels:
      - "autoheal=true"
    restart: unless-stopped

  ipfs:
    build: ./ipfs
    image: chainify/engine-ipfs
    container_name: engine-ipfs
    volumes:
      - ~/.data/ipfs/nolik/data:/data/ipfs
      - ~/.data/ipfs/nolik/staging:/export
    ports:
      - 4001:4001
      - 5001:5001
    restart: unless-stopped
    tty: true
    stdin_open: true

  autoheal:
    build: ./autoheal
    image: chainify/engine-autoheal
    container_name: engine-autoheal
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal